### PR TITLE
Refactor clean template

### PR DESCRIPTION
**Pull request by omegamvc**
This pull request includes the initial refactor of the clean template. The following changes have been made:

Refactored all occurrences of .types to .type to align with the updated method in CanHaveAType.
Added a check that ensures the Charts menu does not appear when the --setting=graphs.enabled=true flag is not set, based on a feature implemented in the default template.
Addressed deprecated warnings related to the getTypes method of the CanHaveAType trait.
The changes aim to improve compatibility and enhance the user experience by reducing unnecessary deprecation warnings and ensuring cleaner template behavior.

Please review the changes and let me know if there are any further adjustments required.

### CODE REVIEW

**Review by jaapio — APPROVED** [review]
Thanks, I do not see any issues in the changes you did. So I will merge this soon to the main branch. 

A small remark for future changes, it might be useful to split the larger files into separate component templates like we did for the default template. That will help you to reduce the number of changes you have to repeat. It's a very long time ago since I looked at this template. So I don't know the options. But it might help you in maintaining the template.

**Comment by jaapio** [comment]
As you can see the cypress test on the clean template did fail. It would be nice if you could have a look at those. 

You can run them local using: `make e2e-test` when you have docker installed on your dev machine.

**Comment by omegamvc** [comment]
Unfortunately, you don't use Docker. It would be great if it could be done in another way.

**Comment by omegamvc** [comment]
> Grazie, non vedo alcun problema nelle modifiche che hai fatto. Quindi unirò presto questo al ramo principale.
> 
> Una piccola osservazione per i cambiamenti futuri: potrebbe essere utile dividere i file più grandi in template di componenti separati, come abbiamo fatto per il template predefinito. Ciò ti aiuterà a ridurre il numero di cambiamenti che devi ripetere. È passato molto tempo dall'ultima volta che ho guardato questo template. Quindi non conosco le opzioni. Ma potrebbe aiutarti a mantenere il template.

Splitting the files into smaller individual components, as was done with the default template, is one of the things I will do as soon as possible, and I agree that they are much more maintainable than long and complex files.

**Comment by omegamvc** [comment]
I noticed that for some reason, in the pull request I made, there are many files that I didn't modify. I don't know why I was assigned files that aren't mine. The point is that the copy that's online doesn't compile correctly, but the one I have locally does. Could you please delete my pull requests so I can redo them and hopefully they'll be fine? Thank you

**Comment by jaapio** [comment]
You can just close a pr and remove the branch from your own fork. There is no action required from my side.

**Pull request closed without merging**
