### PR TITLE
Detect null elements in Collection

### PR DESCRIPTION
**Pull request by orklah**
Draft for working with CI

### CODE REVIEW

**Comment by orklah** [comment]
The only null I spotted was in a recent test.

Either the issue with null introduction was fixed earlier, or the issue is not reproduced with the tests nor smoke test.

The assertion I added ensure we don't ever add null into Collections but I'm not sure if you want to keep them on production.

**Comment by jaapio** [comment]
I mentioned the filters as a possible hotspot of null values. I need to check what is exactly implemented there. I think it is OK to have the assets in place because that reduces the number of checks we have to do at other locations. If we can get rid of these null value issues that would be very nice. 

Keep up the good work!

**Comment by orklah** [comment]
I'll put that one ready, I'll look at filters on another PR

**Comment by jaapio** [comment]
Thanks for these improvements

**Pull request merged**
