### PR TITLE
Fix string class names in tests

### PR DESCRIPTION
**Pull request by 50bhan**
This PR will close issue #2215

### CODE REVIEW

**Comment by mvriel** [comment]
Hi @50bhan, 

Thank you for your Pull Request! I am oh so grateful to be rid of this bit of legacy, so this is perfect. I am afraid PHPCS is going to complain because we sort the imports alphabetically and grouped by class, function and constant.

I can fix that for you, or you can update the PR yourself; just let me know :)

**Comment by 50bhan** [comment]
@mvriel Hi,

No problem. Yes getting rid of legacy is really nice. Oh ok, I didn't knew this. I thought some style service will fix it. So I will fix it.

**Comment by jaapio** [comment]
I'm not sure if you have a machine running docker. But our setup contains a make file that helps you with the most common development tasks. 

`make phpcbf` will fix the cs issues. 
`make pre-commit-test` will help you to validate what you are commiting. 

it will require docker as said. 

Thanks for your time and efforts!

**Comment by 50bhan** [comment]
@jaapio Actually I do run a docker on my machine. But I ran all of my projects inside a docker container. Your approach will work if I run this project on my host machine and then run tests inside a docker container. Correct me if I'm wrong.

**Comment by jaapio** [comment]
That's true, the docker setup of this project will run all tests inside a container. The make commands will mount the directories from your host machine into the docker container. So phpcs will be able to do the checks.

**Comment by mvriel** [comment]
Thank you so much @50bhan! I have merged your PR and it is on its way through the pipeline. Welcome to the list of contributors for phpDocumentor :)

**Pull request merged**
