### PR TITLE
experiment with getTypes

### PR DESCRIPTION
**Pull request by orklah**

### CODE REVIEW

**Comment by orklah** [comment]
Well, best I could do is use the same trick as in TypedAbstract and array_filter the getType result to be sure not to return null.

**Comment by orklah** [comment]
This will close #2248

**Comment by orklah** [comment]
This should be good to merge too if you think it's worth it. The CI fail is not related

**Comment by orklah** [comment]
I don't get it, build fails spectacularly but there's almost nothing on this PR. It didn't seem to affect other PR though...

**Comment by jaapio** [comment]
I think we need to update our ci setup. But due to different priorities I didn't get to that yet. 

No worries as soon as I have fixed the ci I will notify you.

**Comment by jaapio** [comment]
Please rebase, let's see if we can merge this one :-)

**Comment by orklah** [comment]
I really don't get it. I'm starting to think there's something wrong with this specific PR... Other PR pass without issue...

**Comment by orklah** [comment]
replaced by #2315

**Pull request closed without merging**
